#!/usr/bin/env bash
echo "--"
echo "-- vim (apt-get)"
echo "--"
sudo apt-get -y install \
    git \
    vim

cd vim 
for dir in *; do
    [ -d "$dir" ] && $dir/init && stow $dir
done
cd ..

curl -fLo ~/.dotfiles/vim/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
