#!/usr/bin/env perl

use strict;
use warnings;
use Term::ANSIColor; 
my %messages = (
  "git pull"       => "yellow",
  "error"          => "red",
  "failed"         => "red",
  "not found"      => "red",
  "newest version" => "green"
);

my $key;
my $value;
my $colored = 0;
while (<>) {
    $colored = 0;
    while (($key, $value) = each (%messages)) {
        $value = $messages{$key};
        if ($_ =~ m/$key/) {
            print color("$value").$_.color("reset");
            $colored = 1;
        }
    }

    if ($colored == 0) {
        print $_;
    }
} 
