#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install \
    stow \
    x11-xkb-utils \
    wget

mkdir -p ~/.local/bin && source ~/.profile

init=(i3 suckless zsh fzf mpd node cmake tmux java nvim vim)
for dir in "${init[@]}"; do
    if [ -d "$dir" ]; then
        $dir/init
        stow $dir
    fi
done
