#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install \
    stow \
    wget

mkdir -p ~/.local/bin && source ~/.profile

init=(i3 mpd node cmake tmux nvim vim)
for dir in "$init[@]"; do
    if [ -d "$dir" ]; then
        $dir/init
        stow $dir
    fi
done
