#!/usr/bin/env bash
sudo apt-get update
sudo apt-get -y install \
    stow \
    wget

for dir in *; do
    if [ -d "$dir" ]; then
        $dir/init
        # stow --ignore=init $dir
        stow $dir
    fi
done
