#!/usr/bin/env bash
echo "--"
echo "-- i3 (apt-get)"
echo "--"
sudo apt-get -y install i3 j4-dmenu-desktop 

cd i3
for dir in *; do
    [ -d $dir  ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd ..

mkdir -p ~/.config/i3
