#!/usr/bin/env bash
echo "--"
echo "-- bspwm (apt-get)"
echo "--"
sudo apt-get -y install bspwm sxhkd suckless-tools j4-dmenu-desktop 

cd bspwm
for dir in *; do
    [ -d $dir  ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd ..

mkdir -p ~/.config/bspwm
