#!/usr/bin/env bash
echo "--"
echo "-- sxhkd (apt-get)"
echo "--"
sudo apt-get -y install sxhkd suckless-tools j4-dmenu-desktop 

cd sxhkd
for dir in *; do
    [ -d $dir  ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd ..

mkdir -p ~/.config/sxhkd
