#!/usr/bin/env bash
VERSION=v16.15.1
echo "--"
echo "-- node $VERSION"
echo "--"
sudo apt-get -y install wget 

cd node
for dir in *; do
    [ -d $dir  ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd .. && pwd

DISTRO=linux-x64
mkdir -p ~/.local && cd /tmp
[ ! -f node-$VERSION-$DISTRO.tar.gz ] && wget --progress=bar http://nodejs.org/dist/$VERSION/node-$VERSION-$DISTRO.tar.gz
tar -xzf node-$VERSION-$DISTRO.tar.gz
cd node-$VERSION-$DISTRO && cp -r * ~/.local
