#!/usr/bin/env bash

VERSION=master
echo "--"
echo "-- i3 $VERSION"
echo "--"
sudo apt-get -y install \
    build-essential \
    automake \
    libev-dev \
    libstartup-notification0-dev \
    libxcb-xkb-dev \
    libxcb-xinerama0-dev \
    libxcb-randr0-dev \
    libxcb-shape0-dev \
    libxcb-util-dev \
    libxcb-cursor-dev \
    libxcb-keysyms1-dev \
    libxcb-icccm4-dev \
    libxcb-xrm-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    libyajl-dev \
    libpcre3-dev \
    libpango1.0-dev \
    vim

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d i3 ]
then
    echo "git checkout $VERSION" && cd i3 && git checkout $VERSION && \
    automake --add-missing && autoreconf && ./configure --prefix=/tmp && cd x86_64-pc-linux-gnu && make -j8 install
else
    echo "git clone https://github.com/i3/i3" && \
    git clone https://github.com/i3/i3 && cd i3 && git checkout $VERSION && \
    automake --add-missing && autoreconf && ./configure --prefix=/tmp && cd x86_64-pc-linux-gnu && make -j8 install
fi

cd /tmp && cd i3-$VERSION && cp -r * ~/.local
