#!/usr/bin/env bash
echo "--"
echo "-- nvim"
echo "--"
sudo apt-get update
sudo apt -y install \
    python3 \
    python3-pip \
    wget \
    xclip

mkdir -p ~/config/nvim

VERSION=v0.4.3
mkdir -p ~/.local && cd /tmp
[ ! -f nvim-linux64.tar.gz ] && wget https://github.com/neovim/neovim/releases/download/$VERSION/nvim-linux64.tar.gz
tar -xzf nvim-linux64.tar.gz
cd nvim-linux64 && cp -r * ~/.local

mkdir -p ~/.dotfiles/vim/.vim && cd ~/.dotfiles/vim/.vim
if [ -d autoload ]
then
    echo "++++++" && cd autoload && git pull --rebase
else
    echo "------" && git clone https://github.com/junegunn/vim-plug autoload
fi

mkdir -p ~/.local/share/nvim/site && cd ~/.local/share/nvim/site
[ ! -f autoload ] && ln -s ~/.dotfiles/vim/.vim/autoload autoload

pip3 install --user neovim
npm install -g neovim
yarn global add neovim

nvim -c 'CocInstall -sync coc-json|q'
