#!/usr/bin/env bash
VERSION=v0.8.0
echo "--"
echo "-- nvim $VERSION"
echo "--"
sudo apt-get -y install \
    curl \
    python3 \
    python3-pip \
    wget \
    xclip

cd nvim
for dir in *; do
    [ -d $dir ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd ..

mkdir -p ~/.config/nvim && mkdir -p ~/.local && cd /tmp
[ ! -f nvim-linux64.tar.gz ] && wget --progress=bar https://github.com/neovim/neovim/releases/download/$VERSION/nvim-linux64.tar.gz
tar -xzf nvim-linux64.tar.gz && cd nvim-linux64 && cp -r * ~/.local

# curl -fLo ~/.dotfiles/nvim/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

