#!/usr/bin/env bash

VERSION=3.6.3
mkdir -p /tmp/forDelete cd /tmp/forDelete
[ ! -f apache-maven-$VERSION-bin.tar.gz ] && wget --progress=bar https://downloads.apache.org/maven/maven-3/$VERSION/binaries/apache-maven-$VERSION-bin.tar.gz

tar -xzf apache-maven-$VERSION-bin.tar.gz
cd apache-maven-$VERSION && tar -tzf /tmp/forDelete/apache-maven-3.6.3-bin.tar.gz | cut -d -f5- | xargs rmdir -p
cd ~/.local && find /tmp/forDelete/apach-maven-$VERSION -type d -empty | cut -d/ -f5- | xargs rmdir -p
