#!/usr/bin/env bash
echo "--"
echo "-- fzf"
echo "--"

if [ -d ~/.fzf ]
then
    echo "git pull --rebase" && cd ~/.fzf && git pull --rebase
else
    echo "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf" && git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
fi
