#!/usr/bin/env bash
echo "--"
echo "-- suckless"
echo "--"
sudo apt-get -y install \
    vim

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d st ]
then
    echo "git pull --rebase" && cd st && git pull --rebase && make
else
    echo "git clone https://git.suckless.org/st" && git clone https://git.suckless.org/st && cd st && make
fi
