#!/usr/bin/env bash
echo "--"
echo "-- suckless"
echo "--"
sudo apt-get -y install \
    libxft-dev \
    vim

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d st ]
then
    echo "git pull --rebase" && cd st && git pull --rebase
else
    echo "git clone https://git.suckless.org/st" && git clone https://git.suckless.org/st && cd st
fi

sed -i 's/char \*termname = "st-256color";/char \*termname = "xterm-256color";/g' config.def.h
make
