#!/usr/bin/env bash

VERSION=javacc-7.0.7
echo "--"
echo "-- javacc $VERSION"
echo "--"
sudo apt-get -y install \
    openjdk-8-jdk \
    ant \
    vim

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d javacc ]
then
    echo "git checkout $VERSION" && cd javacc && git checkout $VERSION && \
    ant dist
else
    echo "git clone https://github.com/javacc/javacc" && \
    git clone https://github.com/javacc/javacc && cd javacc && git checkout $VERSION && \
    ant dist
fi

cp target/$VERSION-distribution.tar.gz /tmp && cd /tmp && \
tar -xzf $VERSION-distribution.tar.gz && cd $VERSION && cp -r * ~/.local
