#! /bin/sh

sxhkd -m 1&
compton &
conky &
# conky -c ~/.config/conky/conky_sys.conf &
# polybar example&

# mkfifo ~/sxhkd.fifo && sxhkd -s ~/sxhkd.fifo &&
 bspc monitor -d I II III IV V VI VII VIII IX X
# INTERNAL_MONITOR="DVI-I-1"
# EXTERNAL_MONITOR="HDMI-0"
# if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
#   xrandr --output ${INTERNAL_MONITOR} --primary --mode 1920x1080 --rotate normal --output ${EXTERNAL_MONITOR} --mode 1920x1080 --rotate normal --left-of ${INTERNAL_MONITOR}
#   bspc monitor "$EXTERNAL_MONITOR" -d VI VII VIII IX X 
#   bspc monitor "$INTERNAL_MONITOR" -d I II III IV V
#   bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
# else
#   bspc monitor -d I II III IV V VI VII VIII IX X
# fi

bspc config ignore_ewmh_focus true

bspc config border_width         1
bspc config normal_border_color  "#000000"
bspc config focused_border_color "#FEFEFE"
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a crawl state=floating
