#! /bin/sh

sxhkd -m 1&
compton &
conky &
# polybar example&

# mkfifo ~/sxhkd.fifo && sxhkd -s ~/sxhkd.fifo &&

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config ignore_ewmh_focus true

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a crawl state=floating
