require('user.settings')
require('user.plugins')
require('user.telescope')
require('user.colorscheme')
require('user.lsp')
require('user.git')
require('user.languagetool')
require('user.zk')
-- require('user.dired')

require('user.keymap')
