#!/usr/bin/env bash

VERSION=master
echo "--"
echo "-- mupdf $VERSION"
echo "--"
sudo apt-get -y install \
    build-essential \
    curl \
    git \
    libglu1-mesa-dev \
    libxi-dev \
    libxrandr-dev \
    mesa-common-dev \
    vim

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d mupdf ]
then
    echo "git checkout $VERSION" && cd mupdf && git checkout $VERSION && \
    make prefix=/tmp/mupdf-$VERSION install
else
    echo "git clone --recursive git://git.ghostscript.com/mupdf.git" && \
    git clone --recursive git://git.ghostscript.com/mupdf.git && cd mupdf && git checkout $VERSION && \
    make prefix=/tmp/mupdf-$VERSION install
fi

cd /tmp && cd mupdf-$VERSION && cp -r * ~/.local
