#!/usr/bin/env bash

VERSION=master
echo "--"
echo "-- mupdf $VERSION"
echo "--"
sudo apt-get -y install \
    build-essential \
    curl \
    git \
    libglu1-mesa-dev \
    libxi-dev \
    libxrandr-dev \
    mesa-common-dev \
    vim

cd mupdf
for dir in *; do
    [ -d $dir  ] && [ -f $dir/init ] && $dir/init && stow $dir -t ~
done
cd ..

mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d mupdf ]
then
    echo "git checkout $VERSION" && cd mupdf && git checkout $VERSION
else
    echo "git clone --recursive git://git.ghostscript.com/mupdf.git" && \
    git clone --recursive git://git.ghostscript.com/mupdf.git && cd mupdf && git checkout $VERSION
fi

[ ! -d /tmp/mupdf-$VERSION ] && make prefix=/tmp/mupdf-$VERSION install && cd /tmp && tar -czf mupdf-$VERSION.tar.gz mupdf-$VERSION
cd /tmp && cd mupdf-$VERSION && cp -r * ~/.local
