#!/usr/bin/env bash
echo "--"
echo "-- tmux"
echo "--"
sudo apt update
sudo apt -y install \
    autoconf \
    automake \
    bison \
    build-essential \
    curl \
    git \
    libevent-dev \
    libncurses5-dev \
    pkg-config \
    vim

mkdir -p ~/dev/git && cd ~/dev/git
if [ -d tmux ]
then
    echo "++++++" && cd tmux && git pull --rebase && make
else
    echo "------" && git clone https://github.com/tmux/tmux.git && cd tmux && ./autogen.sh && ./configure && make
fi
