#!/usr/bin/env bash
echo "--"
echo "-- tmux"
echo "--"
sudo apt-get -y install \
    autoconf \
    automake \
    bison \
    build-essential \
    curl \
    git \
    libevent-dev \
    libncurses5-dev \
    pkg-config \
    vim

VERSION=3.1
mkdir -p ~/.local/bin
mkdir -p ~/dev/git && cd ~/dev/git
if [ -d tmux ]
then
    echo "git pull --rebase" && cd tmux && git pull --rebase && make
else
    echo "git clone https://github.com/tmux/tmux.git" && git clone https://github.com/tmux/tmux.git && cd tmux && ./autogen.sh && ./configure --prefix=/tmp/tmux-3.1 && make install
fi

cd /tmp && tar -czf tmux-$VERSION.tar.gz tmux-$VERSION
