#!/usr/bin/env bash
echo "--"
echo "-- zsh"
echo "--"
sudo apt-get -y install zsh
ps -p $$ | grep zsh > /dev/null && chsh -s $(which zsh)

if [ -d ~/.oh-my-zsh ]
then
    echo "git pull --rebase" && cd ~/.oh-my-zsh && git pull --rebase
else
    echo "git clone https://github.com/ohmyzsh/ohmyzsh.git" && git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
fi

cd ~/dev/git
if [ -d fasd ]
then
    echo "git pull --rebase" && cd fasd && git pull --rebase && make PREFIX=~/.local install
else
    echo "git clone https://github.com/clvv/fasd.git" && git clone https://github.com/clvv/fasd.git && cd fasd && make PREFIX=~/.local install
fi
