#!/usr/bin/env bash
echo "--"
echo "-- zsh (apt-get)"
echo "--"
sudo apt-get -y install zsh
ps -p $$ | grep zsh > /dev/null && chsh -s $(which zsh)

for dir in zsh/*; do
    [ -d "$dir" ] && $dir/init && stow $dir
done
