#!/usr/bin/env bash

VERSION=3.17.2
mkdir -p /tmp/forDelete && cd /tmp/forDelete
[ ! -f cmake-$VERSION-Linux-x86_64.tar.gz ] && wget --progress=bar https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION-Linux-x86_64.tar.gz

tar -xzf cmake-$VERSION-Linux-x86_64.tar.gz
cd cmake-$VERSION-Linux-x86_64 && tar -tzf /tmp/forDelete/cmake-$VERSION-Linux-x86_64.tar.gz | cut -d/ -f2- | sed 's/ /\\ /g' | xargs rm 2> /dev/null
cd ~/.local                    && tar -tzf /tmp/forDelete/cmake-$VERSION-Linux-x86_64.tar.gz | cut -d/ -f2- | sed 's/ /\\ /g' | xargs rm 2> /dev/null
cd ~/.local && find /tmp/forDelete/cmake-$VERSION-Linux-x86_64 -type d -empty | cut -d/ -f5- | xargs rmdir -p 2> /dev/null
