#!/usr/bin/env bash
echo "--"
echo "-- cmake"
echo "--"
sudo apt-get -y install wget 

VERSION=3.17.2
mkdir -p ~/.local && cd /tmp
[ ! -f cmake-$VERSION-Linux-x86_64.tar.gz ] && wget --progress=bar https://github.com/Kitware/CMake/releases/download/v$VERSION/cmake-$VERSION-Linux-x86_64.tar.gz

tar -xzf cmake-$VERSION-Linux-x86_64.tar.gz
cd cmake-$VERSION-Linux-x86_64 && cp -r * ~/.local
